version: '3.8'

services:
  llmitless_app:
    container_name: LLMitless_PROD
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: production
      args:
        PROJECT_ROOT: /LLMitless
        APPLICATION_PROD_SERVER_PORT: 80      
    env_file:
      - ../.env.prod
    environment:
      - ENV_CONTEXT=production
    ports:
      - "80:80"
    command: ["uvicorn", "src.serve:app", "--host", "0.0.0.0", "--port", "80"]
    restart: unless-stopped