version: '3.8'

services:
  llmitless_app:
    container_name: LLMitless_DEV
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: development
      args:
        # A list of whatever tools you'll use in development.
        # Pass multiple packages as a space-separated string eg. "nano curl cowsay"
        ADD_SYSTEM_LEVEL_PACKAGES: "nano" 
        PROJECT_ROOT: /LLMitless
        APPLICATION_DEV_SERVER_PORT: 50201
    ports:
      - "50201:50201"
    environment:
      - ENV_CONTEXT=development
    volumes:
      - ..:/LLMitless
    command: ["uvicorn", "src.serve:app", "--reload", "--host", "0.0.0.0", "--port", "50201"]
    restart: unless-stopped


  ngrok:
    image: ngrok/ngrok
    env_file:
      - ../.env
    
    # The env_file option passes vars from files directly to container, so they're not
    # available in Compose file. We use a script to get them from environment @ runtime.
    # The ngrok container has a baked-in entrypoint script that will use these args, but
    # that script can't access env vars, so we get them with custom script, then call original entrypoint
    entrypoint: >
      /bin/sh -c '
      EDGE_VALUE=$$NGROK_EDGE;
      exec /entrypoint.sh tunnel --label edge="$$EDGE_VALUE" llmitless_app:50201
      '
    ports:
      - "4040:4040" # Optional: Expose ngrok web interface
    depends_on:
      - llmitless_app
    restart: unless-stopped