version: '3.8'

services:
  llmitless_app:
    container_name: LLMitless_DEV
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: development
      args:
        # A list of whatever tools you'll use in development.
        # Pass multiple packages as a space-separated string eg. "nano curl cowsay"
        ADD_SYSTEM_LEVEL_PACKAGES: "nano" 
        PROJECT_ROOT: /LLMitless
        APPLICATION_DEV_SERVER_PORT: 50201
    ports:
      - "50201:50201"
    environment:
      - FASTAPI_ENV=development
    volumes:
      - ..:/LLMitless
    command: ["uvicorn", "src.serve:app", "--reload", "--host", "0.0.0.0", "--port", "50201"]
    restart: unless-stopped


  ngrok:
    image: ngrok/ngrok
    env_file:
      - ../.env
    # The env_file option passes vars from files directly to container, so they're not
    # available in Compose file. We use a script to get them from environment @ runtime.
    # The ngrok container has a baked-in entrypoint script that will use these args 
    command: tunnel --label edge=edghts_2VTFyUW2cVDTiBC7EDyw3j6Qt06 llmitless_app:50201
    # command: http --domain="$${NGROK_DOMAIN}" llmitless_app:50201
    # command: /bin/sh "ngrok http $${NGROK_DOMAIN}:50201"
    ports:
      - "4040:4040" # Optional: Expose ngrok web interface
    depends_on:
      - llmitless_app
    restart: unless-stopped