version: '3.8'

services:
  app:
    container_name: LLMitless_DEV
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: development
    ports:
      - "50201:50201"
    environment:
      - FASTAPI_ENV=development
    volumes:
      - ..:/LLMitless
    command: ["uvicorn", "src.serve:app", "--reload", "--host", "0.0.0.0", "--port", "50201"]