version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: production
    env_file:
      - ./.env
    environment:
      - FASTAPI_ENV=production
    ports:
      - "80:80"
    command: ["uvicorn", "src.serve:app", "--host", "0.0.0.0", "--port", "80"]
    restart: unless-stopped