version: '3.8'

services:
  llmitless_app:
    container_name: LLMitless_TEST
    env_file: ../.env # GH Actions should create a .env file in project root
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: test-image
      args:
        PROJECT_ROOT: /LLMitless
        APPLICATION_PROD_SERVER_PORT: 80
    environment:
      - ENV_CONTEXT=test
    command: ["poetry", "run", "pytest", "-vv", "-s"]