version: '3.8'

services:
  llmitless_app:
    container_name: LLMitless_TEST
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: test-image
      args:
        PROJECT_ROOT: /LLMitless
        APPLICATION_PROD_SERVER_PORT: 80      
    env_file:
      - ../.env.test
    environment:
      - ENV_CONTEXT=test
    command: ["poetry", "run", "pytest", "-vv"]