version: '3.8'

services:
  llmitless_app:
    container_name: LLMitless_DEV
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: development
      args:
        # A list of whatever tools you'll use in development.
        # Pass multiple packages as a space-separated string eg. "nano curl cowsay"
        ADD_SYSTEM_LEVEL_PACKAGES: "nano" 
        PROJECT_ROOT: /LLMitless
        APPLICATION_DEV_SERVER_PORT: 50201
    ports:
      - "50201:50201"
    environment:
      - FASTAPI_ENV=development
    volumes:
      - ..:/LLMitless
    command: ["uvicorn", "src.serve:app", "--reload", "--host", "0.0.0.0", "--port", "50201"]
    depends_on:
      - ngrok

  ngrok:
    image: ngrok/ngrok
    env_file:
      - ../.env
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: http ${NGROK_DOMAIN}:50201
    ports:
      - "4040:4040" # Optional: Expose ngrok web interface