version: '3.8'

services:
  llmitless_app:
    container_name: LLMitless_PROD
    image: ${DOCKER_IMAGE_NAME_PROD:-llmitless_prod:latest}
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: production
      args:
        PROJECT_ROOT: /LLMitless
        APPLICATION_PROD_SERVER_PORT: 8080      
    environment:
      - ENV_CONTEXT=production
    ports:
      - "8080:8080"
    restart: unless-stopped