name: Tests

on:
  push:
    branches:
      - main

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build and test
        env:
            PYTHONTRACEMALLOC: ${{ env.PYTHONTRACEMALLOC }}
            PYTHONASYNCIODEBUG: ${{ env.PYTHONASYNCIODEBUG }}
            WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        run: docker compose -f docker/docker-compose.test-image.yml run llmitless_app