name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Prepare environment variables file
        run: |
          cat <<EOF >.env
          PYTHONTRACEMALLOC=${{ vars.PYTHONTRACEMALLOC }}
          PYTHONASYNCIODEBUG=${{ vars.PYTHONASYNCIODEBUG }}
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
          EOF

      - name: Build and test
        run: docker compose -f docker/docker-compose.test-image.yml run llmitless_app